[package]
name = "home-assistant-airtag-importer"
version = "0.1.1"
edition = "2021"
description = "Export, convert, and diagnose Find My accessories for Home Assistant"

[dependencies]
rustpush = { git = "https://github.com/johncattrall/rustpush.git", rev = "299e4389b7bc68123922c651da92dac8ac45c989", default-features = false, features = ["remote-anisette-v3"] }
omnisette = { git = "https://github.com/johncattrall/rustpush.git", rev = "299e4389b7bc68123922c651da92dac8ac45c989" }
icloud_auth = { git = "https://github.com/johncattrall/rustpush.git", rev = "299e4389b7bc68123922c651da92dac8ac45c989", default-features = false, features = ["remote-anisette-v3"] }
keystore = { git = "https://github.com/johncattrall/rustpush.git", rev = "299e4389b7bc68123922c651da92dac8ac45c989" }
cloudkit-proto = { git = "https://github.com/johncattrall/rustpush.git", rev = "299e4389b7bc68123922c651da92dac8ac45c989" }
tokio = { version = "1", features = ["full"] }
plist = "1.7.0"
sha2 = "0.10.8"
async-trait = "0.1.73"
uuid = { version = "1.4.1", features = ["v4"] }
rand = "0.8.5"
libc = "0.2"
pretty_env_logger = "0.5.0"
clap = { version = "4", features = ["derive", "env"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
chrono = { version = "0.4", features = ["serde"] }
